include: [./docker/traefik/service.yaml]

services:
  frontend:
    image: knplabs/hot-tools:frontend-${IMAGE_TAG:-latest}
    env_file: .env
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      target: dev
    volumes:
      - ./apps/frontend:/app
    networks:
      - default
      - playwright-test-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  php:
    platform: linux/x86_64
    image: knplabs/hot-tools:php-${IMAGE_TAG:-latest}
    env_file: .env
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    volumes:
      - ./apps/backend:/app
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: base
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/backend/public:/app/public
    restart: unless-stopped
    depends_on:
      php:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`localhost`) && PathPrefix(`/graphql`) 
        || Host(`localhost`) && PathPrefix(`/_profiler`) 
        || Host(`localhost`) && PathPrefix(`/graphiql`)
        || Host(`localhost`) && PathPrefix(`/slack`)
        || Host(`localhost`) && PathPrefix(`/logout`)"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  adminer:
    image: adminer:4.8.1
    ports:
      - 8888:8080

  playwright:
    env_file: .env
    build:
      context: .
      dockerfile: docker/playwright/Dockerfile
    volumes:
      - ./apps/frontend/e2e:/home/pwuser/e2e
      - ./apps/frontend/playwright.config.ts:/home/pwuser/playwright.config.ts
    networks:
      - playwright-test-network
    depends_on:
      frontend:
        condition: service_started
    ipc: host

volumes:
  database:

networks:
  playwright-test-network:
    driver: bridge
